### PR TITLE
Removed gradient from list of posts

### PR DESCRIPTION
**Pull request by dylan-smith**
I didn't like the gradient, I think it looks better without. What do you think?

### CODE REVIEW

**Comment by MisterJames** [comment]
Picture? You can paste here.

**Comment by dylan-smith** [comment]
image

**Comment by kbaley** [comment]
I could be convinced to remove the gradient here but I believe it still needs a faint line separating them.

That said, see what the full list of posts/podcasts looks like without it first. This is fine because it's only five posts. I think gradient does a better job of separating the posts when there's a long list. Otherwise, it's a big sea of white with text on it.

**Comment by dpaquette** [comment]
Maybe just the to border like we have on the Speaking section in the main page?

**Comment by MisterJames** [comment]
Yeah, it needs some separation. I don't mind the gradient, especially when you let the text flow (like in #142 ) but it doesn't have to be so pronounced.

**Comment by kbaley** [comment]
Here's how it would look on the post listing (with a fixed header):

image

**Pull request closed without merging**
